/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2018-08-23 17:26:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>LoginScreen</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".header1 {\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header2 {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-top: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".services {\r\n");
      out.write("\twidth: 22%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".departments {\r\n");
      out.write("\twidth: 22%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".apointment {\r\n");
      out.write("\twidth: 28%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("\twidth: 28%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 75px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #008ae6; color: white;\">\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"height: 85px\" align=\"center\">\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<h1>A J Hospital and Research Centre</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header2\" align=\"left\">\r\n");
      out.write("\t\t\t<h2>A unit of AJ Charitable Trust(R)</h2>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"height: 368px\">\r\n");
      out.write("\t\t<div class=\"services\">\r\n");
      out.write("\t\t\t<h3>Our Services</h3>\r\n");
      out.write("\t\t\t<li>Ambulance</li>\r\n");
      out.write("\t\t\t<li>Day Care</li>\r\n");
      out.write("\t\t\t<li>Pharmacy</li>\r\n");
      out.write("\t\t\t<li>Laboratory</li>\r\n");
      out.write("\t\t\t<li>Pysiotherapy</li>\r\n");
      out.write("\t\t\t<li>Diet Service</li>\r\n");
      out.write("\t\t\t<li>Paediatrics</li>\r\n");
      out.write("\t\t\t<li>Plastic Surgery</li>\r\n");
      out.write("\t\t\t<li>Radio Diagnosis</li>\r\n");
      out.write("\t\t\t<li>Health Check Up</li>\r\n");
      out.write("\t\t\t<li>Special Equipment</li>\r\n");
      out.write("\t\t\t<li>Home Health Services</li>\r\n");
      out.write("\t\t\t<li>Emergency/Trauma</li>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"departments\">\r\n");
      out.write("\t\t\t<h3>Departments</h3>\r\n");
      out.write("\t\t\t<li>ENT</li>\r\n");
      out.write("\t\t\t<li>Oncology</li>\r\n");
      out.write("\t\t\t<li>Urology</li>\r\n");
      out.write("\t\t\t<li>Neurology</li>\r\n");
      out.write("\t\t\t<li>Orthopaedics</li>\r\n");
      out.write("\t\t\t<li>Endocrinology</li>\r\n");
      out.write("\t\t\t<li>Cardiology</li>\r\n");
      out.write("\t\t\t<li>Dermatology</li>\r\n");
      out.write("\t\t\t<li>Psychiatry</li>\r\n");
      out.write("\t\t\t<li>Endocrinology</li>\r\n");
      out.write("\t\t\t<li>Gastroenterology</li>\r\n");
      out.write("\t\t\t<li>Ophthalmology & ENT</li>\r\n");
      out.write("\t\t\t<li>Obstetrics & Gynecology</li>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"apointment\">\r\n");
      out.write("\t\t\t<h3>Book an Appointment</h3>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/Controller\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Patient Status</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"radio\" name=\"visitType\" value=\"new\" checked />New\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"visitType\" value=\"revisit\" />Revisit\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Booking Date:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"date\" id=\"myDate\" value=\"15-08-2018\" size=\"20\" required style=\"width:157px\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100px\">Doctor:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"doctorName\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan='3' align=\"center\">OR</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Department:</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select  name=\"department\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option ></option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ent\">ENT</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"oncology\">Oncology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"urology\">Urology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"neurology\">Neurology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"orthopaedics\">Orthopaedics</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"endocrinology\">Endocrinology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"cardiology\">Cardiology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"dermatology\">Dermatology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"endocrinology\">Endocrinology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gastroenterology\">Gastroenterology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ophthalmology\">Ophthalmology</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gynecology\">Obstetrics&Gynecology</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Patient Name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" required name=\"pName\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Address:</td>\r\n");
      out.write("\t\t\t\t\t<td><input minlength=\"20\" required name=\"address\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Mob:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\"  name=\"mob\" maxlength=\"10\" required /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t<td colspan='3'><button type=\"submit\" value=\"Booking\" name=\"submit\">Book </button>\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"login\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h4>Office Use Only</h4>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/Controller\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>User Name</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan='2'>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"userId\" type=\"text\" required name=\"userId\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Password</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan='2'><input id=\"password\" type=\"password\" name=\"password\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan='3'><input type=\"submit\" id=\"Log\" value=\"Login\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"submit\" /> <input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t<p>Contact Us: MG Road Chikkamagaluru Karnataka - 577100\r\n");
      out.write("\t\tMob:9800098000 E-Mail:ajhospital@ajcharitables.com © 2018 AJHospital.\r\n");
      out.write("\t\tAll Rights Reserved</p>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
